# Generated by Django 4.2.8 on 2023-12-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0002_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_post',
            name='category',
            field=models.CharField(choices=[('Data Structures', 'Data Structures'), ('Mathematics', 'Mathematics'), ('Information Technology', 'Information Technology'), ('Programming Language', 'Programming Language'), ('Software Development', 'Software Development'), ('Algorithms', 'Algorithms'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Neural Networks', 'Neural Networks'), ('Others', 'Others')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
