# Generated by Django 4.2.8 on 2023-12-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0003_alter_article_post_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='video',
            new_name='article',
        ),
    ]
